[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "polkadot-local"
chain_spec_command = "./bin/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 3369
chain = "mainnet-local-v"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9920
    command = "./target/release/mythos-node"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator2"
    command = "./target/release/mythos-node"
    args = [ "-lxcm=trace", "--state-cache-size=0"]
